# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# @see org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
# @see org.springframework.boot.autoconfigure.liquibase.LiquibaseProperties
liquibase:
    enabled: true
    contexts: prod
    changeLog: classpath:config/liquibase/master.xml

multipart:
    enabled: true
    # Threshold after which files will be written to disk.
    file-size-threshold: 0
    # Intermediate location of uploaded files.
    # location:
    # Max file size.
    max-file-size: 50Mb
    max-request-size: 200Mb

security.basic.enabled: false

spring:
    data.jpa.repositories.enabled: true
    data.rest:
        basePath: /rest
        pageParamName: page
        limitParamName: size
        sortParamName: sort
        default-page-size: 100
        max-page-size: 1000
        return-body-on-create: false
        return-body-on-update: false

    # @see org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    # @see org.springframework.boot.autoconfigure.jdbc.DataSourceProperties
    # pool type
    # org.apache.tomcat.jdbc.pool.DataSource
    # com.zaxxer.hikari.HikariDataSource
    # org.apache.commons.dbcp.BasicDataSource
    # org.apache.commons.dbcp2.BasicDataSource
    datasource:
        # populate using data.sql
        initialize: false
        jmx-enabled: false
        # tomcat pool
        validation-query: select 1
        # Hikari
        connectionTestQuery: select 1

    http:
        # enable http encoding support
        encoding.enabled: true
        converters.preferred-json-mapper: gson

    mail:
        host: localhost
        port: 25
        username:
        password:
        protocol: smtp
        tls: false
        auth: false
        from: judge@localhost

# @see org.springframework.boot.autoconfigure.orm.jpa.JpaProperties
    jpa:
        show-sql: true
        hibernate.ddl-auto: none
        #hibernate.naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate:
                cache:
                    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
                    use_query_cache: false
                    use_second_level_cache: true
#                dialect:

                generate_statistics: false

                query.substitutions: true '1', false '0'

            javax.persistence.jdbc.validation.mode: none

    # THYMELEAF (org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration)
    thymeleaf:
        mode: XHTML
        prefix: /WEB-INF/templates/
        suffix: .xhtml
        cache: false
