# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: judge@localhost

swagger:
    title: judge API
    description: judge applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

server:
    port: 8080

liquibase:
    context: prod

spring:
    profiles:
        active: prod

# @see org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# @see org.springframework.boot.autoconfigure.jdbc.DataSourceProperties
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb:///oj?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
        username: root
        password: root

    jpa:
        hibernate:
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            javax.persistence:
                jdbc:
                    url: jdbc:mariadb:///oj?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
                    driver: org.mariadb.jdbc.Driver
                    user: root
                    password: root
                validation.mode: none

            hibernate:
                connection.provider_class: com.jolbox.bonecp.provider.BoneCPConnectionProvider
                cache.provider_class: org.hibernate.cache.NoCacheProvider
                query.substitutions: true '1', false '0'

                cache:
                    use_second_level_cache: true
                    use_query_cache: false
                    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

                generate_statistics: false

                hbm2ddl:
                    auto: update
                    import_files: /0000data.sql
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

            bonecp:
                idleConnectionTestPeriodInMinutes: 14400
#                initialPoolSize: 1
#                acquireIncrement: 1
                connectionTestStatement: select 1
                logStatementsEnabled: true

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: judge

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
