spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/oj?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
        username: root
        password: root

    profiles.include: prod
