spring:
    profiles:
        active: prod

    datasource:
        url: jdbc:mariadb:///oj?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root

