# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: true

mail:
    host: localhost
    port: 25
    username:
    password:
    protocol: smtp
    tls: false
    auth: false
    from: judge@localhost

swagger:
    title: ZJNU Judge Online
    description: judge applications and beyond!
    termsOfServiceUrl: http://github.com/zhanhb/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

server.port: 8080

# @see org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
# @see org.springframework.boot.autoconfigure.liquibase.LiquibaseProperties
liquibase:
    enabled: true
    contexts: prod, test
    changeLog: classpath:config/liquibase/master.xml

spring:
# @see org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# @see org.springframework.boot.autoconfigure.jdbc.DataSourceProperties
# pool type
# org.apache.tomcat.jdbc.pool.DataSource
# com.zaxxer.hikari.HikariDataSource
# org.apache.commons.dbcp.BasicDataSource
# org.apache.commons.dbcp2.BasicDataSource
    datasource:
        # populate using data.sql
        initialize: false
        jmx-enabled: false
        # tomcat pool
        validation-query: select 1
        # Hikari
        connectionTestQuery: select 1

# @see org.springframework.boot.autoconfigure.orm.jpa.JpaProperties
    jpa:
        show-sql: true
        hibernate.ddl-auto: none
        #hibernate.naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            javax.persistence.jdbc.validation.mode: none

            hibernate:
#                dialect:
                query.substitutions: true '1', false '0'

                cache:
#                    provider_class: org.hibernate.cache.NoCacheProvider
                    use_second_level_cache: true
                    use_query_cache: false
                    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

                generate_statistics: false

    thymeleaf:
        mode: XHTML
        cache: true
    application.admin.enabled: true
    hateoas.apply-to-primary-object-mapper: true

metrics:
    jmx.enabled: false
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: judge

http.cache.timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache.maxBytesLocalHeap: 256M

# encoding will be filtered by this filter
# see com.github.zhanhb.judge.config.EncodingFilterInitializer
# see https://github.com/zhanhb/character-encoding-filter/
server.tomcat.uri-encoding: ISO-8859-1
spring.http:
# enable http encoding support
    encoding.enabled: false
    converters.preferred-json-mapper: gson

multipart:
    enabled: true
    # Threshold after which files will be written to disk.
    file-size-threshold: 0
    # Intermediate location of uploaded files.
    # location:
    # Max file size.
    max-file-size: 50Mb
    max-request-size: 200Mb
